### PR TITLE
Route to tracking only on exact remote match

### LINKED ISSUE #61: Cannot create namespaced branches with a slash in the name
Branch creation silently fails as soon as the name contains a `/`.
The modal closes, the working tree stays where it was, and nothing
shows up in the UI. Plain names like `PROJ-1-foo` work; namespaced
ones like `feature/PROJ-1-foo` don't.

Any name with a slash is treated as a remote branch and ends up in
`git checkout -b <suffix> --track <full-name>`, which fails because
no such remote exists. Stderr is not surfaced, so the failure is
invisible.

This makes namespaced branch templates effectively unusable,
including the `{{.ParentKey}}/...` patterns from #29.

**Proposal**

Route to tracking only when the entered name exactly matches an
existing entry from `git branch -r`. Otherwise create a new local
branch.

Resolution order:

1. Local branch with that name exists -> `git checkout`
2. Exact remote match -> `git checkout -b <local> --track <remote>`
3. Otherwise -> `git checkout -b <name>`

Strict equality, not prefix match: an existing `origin/feature/x`
must not capture a new `origin/feature/y`.

I have this implemented and can open a PR.

### PR DESCRIPTION
**Pull request by seflue**
Closes #61

The branch modal now treats the input as a tracking branch only
when the name exactly matches an entry from `git branch -r`.
Anything else becomes a new local branch.

The decision is extracted into `pkg/git` so it can be covered by a
fixture-based test without spinning up the TUI.

**To test:** in a repo with `origin/main` only, confirm a name like
`feature/PROJ-1-foo` from the branch modal. The local branch is
created, no error.

### CODE REVIEW

File: pkg/git/branch.go [hunk 1]
```diff
@@ -69,6 +70,39 @@ func RemoteBranches(dir string) ([]string, error) {
...
+func ResolveBranchAction(dir, name string) BranchAction {
+	switch {
+	case BranchExists(dir, name):
+		return ActionCheckout
+	case IsRemoteBranch(dir, name):
+		return ActionCheckoutTracking
+	default:
+		return ActionCreate
+	}
+}
```
Comment (textfuel) [inline pkg/git/branch.go:104]: could collapse the two switches into one, but not blocking

**Review by textfuel — APPROVED** [review]
Thanks for contributing! PR looks great. I left one comment, but it isn't blocking, feel free to leave it as you have it. I'll merge after your reply

File: pkg/git/branch.go (hunk 1 above)
Comment (seflue) [reply pkg/git/branch.go:104]: Thanks. The split is intentional: ResolveBranchAction is a pure routing function, so branch_test.go can assert the decision directly without exercising real git state. Collapsing it would either move the decision behind a tea.Cmd boundary (harder to unit-test) or fold the side-effects into one function (test setup gets heavier).

Comment (textfuel) [reply pkg/git/branch.go:104]: Fair point! Thanks
